CREATE TABLE IF NOT EXISTS br_states (
id INT AUTO_INCREMENT PRIMARY KEY,
uf VARCHAR(2),
state_name VARCHAR(30) )

INSERT INTO financialdb001.br_states (uf, state_name) VALUES ('RO', 'Rondonia') 
INSERT INTO financialdb001.br_states (uf, state_name) VALUES ('AC', 'Acre')
INSERT INTO financialdb001.br_states (uf, state_name) VALUES ('AM', 'Amazonas')
INSERT INTO financialdb001.br_states (uf, state_name) VALUES ('RR', 'Roraima')
INSERT INTO financialdb001.br_states (uf, state_name) VALUES ('PA', 'Para')
INSERT INTO financialdb001.br_states (uf, state_name) VALUES ('AP', 'Amapa')
INSERT INTO financialdb001.br_states (uf, state_name) VALUES ('TO', 'Tocantins')
INSERT INTO financialdb001.br_states (uf, state_name) VALUES ('MA', 'Maranhao')
INSERT INTO financialdb001.br_states (uf, state_name) VALUES ('PI', 'Piaui')
INSERT INTO financialdb001.br_states (uf, state_name) VALUES ('CE', 'Ceara')
INSERT INTO financialdb001.br_states (uf, state_name) VALUES ('RN', 'Rio Grande do Norte')
INSERT INTO financialdb001.br_states (uf, state_name) VALUES ('PB', 'Paraiba')
INSERT INTO financialdb001.br_states (uf, state_name) VALUES ('PE', 'Pernambuco')
INSERT INTO financialdb001.br_states (uf, state_name) VALUES ('AL', 'Alagoas')
INSERT INTO financialdb001.br_states (uf, state_name) VALUES ('SE', 'Sergipe')
INSERT INTO financialdb001.br_states (uf, state_name) VALUES ('BA', 'Bahia')
INSERT INTO financialdb001.br_states (uf, state_name) VALUES ('MG', 'Minas Gerais')
INSERT INTO financialdb001.br_states (uf, state_name) VALUES ('ES', 'Espirito Santo')
INSERT INTO financialdb001.br_states (uf, state_name) VALUES ('RJ', 'Rio de Janeiro')
INSERT INTO financialdb001.br_states (uf, state_name) VALUES ('SP', 'Sao Paulo')
INSERT INTO financialdb001.br_states (uf, state_name) VALUES ('PR', 'Parana')
INSERT INTO financialdb001.br_states (uf, state_name) VALUES ('SC', 'Santa Catarina')
INSERT INTO financialdb001.br_states (uf, state_name) VALUES ('RS', 'Rio Grande do Sul')
INSERT INTO financialdb001.br_states (uf, state_name) VALUES ('MS', 'Mato Grosso do Sul')
INSERT INTO financialdb001.br_states (uf, state_name) VALUES ('MT', 'Mato Grosso')
INSERT INTO financialdb001.br_states (uf, state_name) VALUES ('GO', 'Goiais')
INSERT INTO financialdb001.br_states (uf, state_name) VALUES ('DF', 'Distrito Federal')
